## PostgreSQL
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/startup-spring-boot-api}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Ca201198}
  jpa:
    generate-ddl: true
    hibernate:
      #   #drop n create table again, good for testing, comment this in production
      ddl-auto: update
    show-sql: true
  flyway:
    locations: classpath:db/migration
    check-location: false
    baseline-on-migrate: true

startup:
  jwtSecret: ${JWT_SECRET:secret}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}